name: na-website
version: '0.0.0'
author: Netizens Association
maintainer: Julian Arni <jkarni@gmail.com>
license: BSD3
git: NetizensAssociation/website

dependencies:
- base >=4 && <5
- aeson
- lens
- network-uri
- servant
- servant-yaml
- servant-server
- text


ghc-options:
  -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

library:
  source-dirs: src
  dependencies: []

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - test/spec
    ghc-options: -threaded
    dependencies:
    - na-website
    - hspec
    - servant-aeson-specs
    - QuickCheck

executables:
  na-server:
    main: Server.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - na-website
    - optparse-applicative
    ghc-options: -main-is Server -O3 -threaded


default-extensions:
- AutoDeriveTypeable
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
